#include "Editor.h"
MorphLook::MorphLook(){setColour(juce::Slider::textBoxTextColourId,juce::Colour(0xffdfebef));setColour(juce::Slider::textBoxOutlineColourId,juce::Colours::transparentBlack);setColour(juce::TextButton::buttonColourId,juce::Colour(0xff23353e));setColour(juce::ComboBox::backgroundColourId,juce::Colour(0xff182830));setColour(juce::ComboBox::outlineColourId,juce::Colour(0xff34464f));}
void MorphLook::drawRotarySlider(juce::Graphics& g,int x,int y,int w,int h,float value,float start,float end,juce::Slider&){auto b=juce::Rectangle<float>(static_cast<float>(x),static_cast<float>(y),static_cast<float>(w),static_cast<float>(h)).reduced(8);float radius=std::min(b.getWidth(),b.getHeight())/2;auto center=b.getCentre();juce::Path track;track.addCentredArc(center.x,center.y,radius,radius,0,start,end,true);g.setColour(juce::Colour(0xff2b3c46));g.strokePath(track,juce::PathStrokeType(3));juce::Path active;active.addCentredArc(center.x,center.y,radius,radius,0,start,start+value*(end-start),true);g.setColour(juce::Colour(0xff82e3ca));g.strokePath(active,juce::PathStrokeType(3));g.setColour(juce::Colour(0xff1d2b34));g.fillEllipse(center.x-radius+7,center.y-radius+7,(radius-7)*2,(radius-7)*2);float angle=start+value*(end-start);g.setColour(juce::Colour(0xffecf4f3));g.drawLine(center.x+std::sin(angle)*(radius-13),center.y-std::cos(angle)*(radius-13),center.x+std::sin(angle)*(radius-22),center.y-std::cos(angle)*(radius-22),2);}
VocalMorphEditor::VocalMorphEditor(VocalMorphProcessor& p):AudioProcessorEditor(p),processor(p){setLookAndFeel(&look);setSize(1100,800);setResizable(true,true);setResizeLimits(960,760,1500,1050);
 for(size_t i=0;i<knobs.size();++i){auto& k=knobs[i];addAndMakeVisible(k);k.setSliderStyle(juce::Slider::RotaryHorizontalVerticalDrag);k.setTextBoxStyle(juce::Slider::TextBoxBelow,false,75,20);k.setDoubleClickReturnValue(true,vm::defaults[i]);attachments.push_back(std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.state,vm::ids[i],k));auto& l=labels[i];addAndMakeVisible(l);l.setText(juce::String(vm::ids[i]).toUpperCase(),juce::dontSendNotification);l.setFont(juce::Font(juce::FontOptions(12)));l.setJustificationType(juce::Justification::centred);}
 for(auto* b:{&load,&save,&open})addAndMakeVisible(*b);addAndMakeVisible(mode);mode.addItem("DSP monitor · zero reported latency",1);mode.addItem("Neural live · 640 ms latency",2);mode.setSelectedId(p.neural?2:1,juce::dontSendNotification);mode.onChange=[this]{processor.setNeuralMode(mode.getSelectedId()==2);};
 addAndMakeVisible(factory);factory.addItemList({"Clean","Pop","Rock","Metal","Character","Creative"},1);factory.setSelectedId(1);factory.onChange=[this]{auto values=vm::defaults;switch(factory.getSelectedId()){case 2:values[3]=.25f;values[5]=.2f;break;case 3:values[6]=.35f;values[4]=.3f;break;case 4:values[6]=.75f;values[8]=.55f;break;case 5:values[0]=-5;values[1]=-3;break;case 6:values[0]=7;values[5]=.7f;break;default:break;}for(size_t i=0;i<values.size();++i){auto* param=processor.state.getParameter(vm::ids[i]);param->beginChangeGesture();param->setValueNotifyingHost(param->convertTo0to1(values[i]));param->endChangeGesture();}};
 addAndMakeVisible(status);status.setFont(juce::Font(juce::FontOptions(13)));addAndMakeVisible(model);model.setText("Your voice. New possibilities.",juce::dontSendNotification);model.setFont(juce::Font(juce::FontOptions(20)));
 load.onClick=[editor=this]{editor->chooser=std::make_unique<juce::FileChooser>("Choose RVC model (.pth)",juce::File(),"*.pth");editor->chooser->launchAsync(juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectFiles,[safe=juce::Component::SafePointer<VocalMorphEditor>(editor)](const juce::FileChooser& f){if(safe&&f.getResult().existsAsFile()){safe->processor.selectModel(f.getResult());safe->model.setText(f.getResult().getFileNameWithoutExtension(),juce::dontSendNotification);}});};
 save.onClick=[editor=this]{editor->chooser=std::make_unique<juce::FileChooser>("Save VocalMorph preset",juce::File(),"*.vmpreset");editor->chooser->launchAsync(juce::FileBrowserComponent::saveMode|juce::FileBrowserComponent::canSelectFiles|juce::FileBrowserComponent::warnAboutOverwriting,[safe=juce::Component::SafePointer<VocalMorphEditor>(editor)](const juce::FileChooser& f){if(safe&&f.getResult()!=juce::File()){juce::MemoryBlock b;safe->processor.getStateInformation(b);f.getResult().withFileExtension("vmpreset").replaceWithData(b.getData(),b.getSize());}});};
 open.onClick=[editor=this]{editor->chooser=std::make_unique<juce::FileChooser>("Load VocalMorph preset",juce::File(),"*.vmpreset");editor->chooser->launchAsync(juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectFiles,[safe=juce::Component::SafePointer<VocalMorphEditor>(editor)](const juce::FileChooser& f){if(safe&&f.getResult().existsAsFile()){juce::MemoryBlock b;if(f.getResult().getSize()<1024*1024&&f.getResult().loadFileAsData(b)){safe->processor.setStateInformation(b.getData(),static_cast<int>(b.getSize()));safe->processor.setNeuralMode(safe->processor.neural);safe->mode.setSelectedId(safe->processor.neural?2:1,juce::dontSendNotification);}}});};startTimerHz(24);}
VocalMorphEditor::~VocalMorphEditor(){stopTimer();setLookAndFeel(nullptr);}
void VocalMorphEditor::timerCallback(){float s;while(processor.meter.pop(s)){waveform[wavePos]=s;wavePos=(wavePos+1)%waveform.size();}status.setText(processor.worker.status()+"  |  Late samples: "+juce::String(processor.underruns.load()),juce::dontSendNotification);repaint(275,80,getWidth()-295,230);}
void VocalMorphEditor::paint(juce::Graphics& g){g.fillAll(juce::Colour(0xff0c131b));g.setColour(juce::Colour(0xff14212b));g.fillRoundedRectangle(16,80,240,static_cast<float>(getHeight()-146),14);g.fillRoundedRectangle(275,80,static_cast<float>(getWidth()-294),230,14);g.setColour(juce::Colour(0xffeaf1f1));g.setFont(juce::Font(juce::FontOptions(27).withStyle("Bold")));g.drawText("VocalMorph",26,20,260,40,juce::Justification::centredLeft);g.setFont(juce::Font(juce::FontOptions(12)));g.setColour(juce::Colour(0xff88a0ad));g.drawText("VOICE TRANSFORMATION STUDIO",300,31,350,24,juce::Justification::centredLeft);g.drawText("MODEL LIBRARY",32,98,210,30,juce::Justification::centredLeft);g.drawFittedText("Import an authorized RVC v1/v2 .pth directly. No manifest JSON is required.\n\nRMVPE and HuBERT support assets may sit beside the .pth or in VocalMorph Resources/assets.\n\nNeural inference runs locally in the bundled worker.\n\nFormant is spectral color. Chromatic tuning applies to neural mode.",32,185,205,275,juce::Justification::topLeft,16);g.drawText("FACTORY PRESETS",32,488,210,28,juce::Justification::centredLeft);
 auto x0=300.f;float width=static_cast<float>(getWidth()-325);g.setColour(juce::Colour(0xff2d424f));g.drawHorizontalLine(231, x0,x0+width);g.setColour(juce::Colour(0xff83e3cd));for(size_t i=0;i<waveform.size();++i){float x=x0+width*static_cast<float>(i)/static_cast<float>(waveform.size());float h=std::min(58.f,std::abs(waveform[(wavePos+i)%waveform.size()])*110);g.drawVerticalLine(static_cast<int>(x),231-h,231+h);}g.setColour(juce::Colour(0xff88a0ad));g.drawText("LIVE INPUT",300,267,180,22,juce::Justification::centredLeft);g.drawText("CHARACTER & FINISH",294,325,300,25,juce::Justification::centredLeft);}
void VocalMorphEditor::resized(){load.setBounds(32,142,207,33);factory.setBounds(32,525,207,32);save.setBounds(32,574,207,32);open.setBounds(32,615,207,32);mode.setBounds(getWidth()-360,26,335,32);model.setBounds(298,102,getWidth()-335,45);status.setBounds(24,getHeight()-46,getWidth()-48,28);int columns=6;int cell=(getWidth()-302)/columns;int rowHeight=(getHeight()-405)/3;for(size_t i=0;i<knobs.size();++i){int x=288+static_cast<int>(i%columns)*cell;int y=365+static_cast<int>(i/columns)*rowHeight;labels[i].setBounds(x,y,cell,18);knobs[i].setBounds(x,y+20,cell,rowHeight-22);}}
