#include "Processor.h"
#include "Editor.h"
juce::AudioProcessorValueTreeState::ParameterLayout VocalMorphProcessor::layout(){juce::AudioProcessorValueTreeState::ParameterLayout p;for(size_t i=0;i<vm::parameterCount;++i)p.add(std::make_unique<juce::AudioParameterFloat>(juce::ParameterID(vm::ids[i],1),juce::String(vm::ids[i]),juce::NormalisableRange<float>(vm::minimum[i],vm::maximum[i],.001f),vm::defaults[i]));return p;}
VocalMorphProcessor::VocalMorphProcessor():AudioProcessor(BusesProperties().withInput("Input",juce::AudioChannelSet::stereo(),true).withOutput("Output",juce::AudioChannelSet::stereo(),true)),state(*this,nullptr,"VocalMorph",layout()){for(size_t i=0;i<raw.size();++i)raw[i]=state.getRawParameterValue(vm::ids[i]);}
bool VocalMorphProcessor::isBusesLayoutSupported(const BusesLayout& b) const {return (b.getMainOutputChannelSet()==juce::AudioChannelSet::mono()||b.getMainOutputChannelSet()==juce::AudioChannelSet::stereo())&&b.getMainInputChannelSet()==b.getMainOutputChannelSet();}
void VocalMorphProcessor::prepareToPlay(double sr,int){rate=sr;clock=0;dryPos=0;hasPending=false;latency=neural?static_cast<int>(sr*.64):0;setLatencySamples(latency);for(auto& d:dsp)d.prepare(sr);for(auto& d:dry)d.assign(static_cast<size_t>(sr)+1,0);++worker.generation;if(modelPath.isNotEmpty())worker.select(juce::File(modelPath),rate);}
void VocalMorphProcessor::setNeuralMode(bool b){suspendProcessing(true);neural=b;latency=b?static_cast<int>(rate*.64):0;setLatencySamples(latency);++worker.generation;hasPending=false;for(auto& d:dry)std::fill(d.begin(),d.end(),0);if(modelPath.isNotEmpty())worker.select(juce::File(modelPath),rate);suspendProcessing(false);}
void VocalMorphProcessor::selectModel(juce::File file){modelPath=file.hasFileExtension("pth")?file.getFullPathName():file.getParentDirectory().getFullPathName();worker.select(juce::File(modelPath),rate);}
void VocalMorphProcessor::processBlock(juce::AudioBuffer<float>& b,juce::MidiBuffer&){process(b,false);}
void VocalMorphProcessor::processBlockBypassed(juce::AudioBuffer<float>& b,juce::MidiBuffer&){process(b,true);}
void VocalMorphProcessor::process(juce::AudioBuffer<float>& b,bool bypass){juce::ScopedNoDenormals guard;int channels=std::min(2,b.getNumChannels());if(dry[0].empty())return;vm::Parameters p;for(size_t i=0;i<raw.size();++i){p.values[i]=raw[i]->load();worker.params[i]=p.values[i];}p.sanitize();bool ai=neural.load();auto q=p;if(ai){q.values[0]=0;q.values[13]=0;}q.values[12]=1;q.values[14]=0;
 auto gen=worker.generation.load();for(int n=0;n<b.getNumSamples();++n,++clock){float mono=0;for(int c=0;c<channels;++c){float s=b.getSample(c,n);dry[static_cast<size_t>(c)][dryPos]=s;mono+=s/channels;}
 if(ai&&!bypass)worker.input.push({mono*std::pow(10.f,p.values[13]/20.f),clock,gen});if(clock%128==0)meter.push(mono);
 bool available=false;float wet=0;
 if(ai&&clock>=static_cast<uint64_t>(latency)){while(worker.output.pop(pending)){if(pending.generation==gen){wet=pending.value;available=true;break;}}if(!available&&worker.ready())++underruns;}
 auto ix=(dryPos+dry[0].size()-static_cast<size_t>(latency))%dry[0].size();for(int c=0;c<channels;++c){float d=dry[static_cast<size_t>(c)][ix];float value=0.f;if(bypass)value=d;else if(ai){if(available){float processed=dsp[static_cast<size_t>(c)].tick(wet,q);value=processed*std::pow(10.f,p.values[14]/20.f);}else value=0.f;}else{float processed=dsp[static_cast<size_t>(c)].tick(d,q);value=(d*(1-p.values[12])+processed*p.values[12])*std::pow(10.f,p.values[14]/20.f);}b.setSample(c,n,value);}dryPos=(dryPos+1)%dry[0].size();}
}
void VocalMorphProcessor::getStateInformation(juce::MemoryBlock& dest){auto s=state.copyState();s.setProperty("modelPath",modelPath,nullptr);s.setProperty("neural",neural.load(),nullptr);if(auto xml=s.createXml())copyXmlToBinary(*xml,dest);}
void VocalMorphProcessor::setStateInformation(const void* data,int size){if(auto xml=getXmlFromBinary(data,size)){auto s=juce::ValueTree::fromXml(*xml);if(s.isValid()&&s.hasType("VocalMorph")){state.replaceState(s);modelPath=s.getProperty("modelPath").toString();neural=static_cast<bool>(s.getProperty("neural",false));if(modelPath.isNotEmpty())worker.select(juce::File(modelPath),rate);}}}
juce::AudioProcessorEditor* VocalMorphProcessor::createEditor(){return new VocalMorphEditor(*this);}
juce::AudioProcessor* JUCE_CALLTYPE createPluginFilter(){return new VocalMorphProcessor();}
